{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--b028011e-bb30-4341-af9f-8f1bb8b203aa",
    "created": "2024-08-13T16:14:12.937015Z",
    "modified": "2024-08-13T16:14:12.937019Z",
    "name": "No Title Available",
    "description": "feedparser.py in Universal Feed Parser (aka feedparser or python-feedparser) before 5.0.1 allows remote attackers to cause a denial of service (application crash) via a malformed DOCTYPE declaration.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2011-1156"
        }
    ],
    "references": [
        {
            "name": "[oss-security] 20110314 CVE request for python-feedparser",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://openwall.com/lists/oss-security/2011/03/14/18"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://support.novell.com/security/cve/CVE-2011-1156.html"
        },
        {
            "name": "43730",
            "tags": [
                "third-party-advisory",
                "x_refsource_SECUNIA"
            ],
            "url": "http://secunia.com/advisories/43730"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://code.google.com/p/feedparser/issues/detail?id=91"
        },
        {
            "name": "46867",
            "tags": [
                "vdb-entry",
                "x_refsource_BID"
            ],
            "url": "http://www.securityfocus.com/bid/46867"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=684877"
        },
        {
            "name": "44074",
            "tags": [
                "third-party-advisory",
                "x_refsource_SECUNIA"
            ],
            "url": "http://secunia.com/advisories/44074"
        },
        {
            "name": "[oss-security] 20110315 Re: CVE request for python-feedparser",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://openwall.com/lists/oss-security/2011/03/15/11"
        },
        {
            "name": "[opensuse-updates] 20110408 openSUSE-SU-2011:0314-1 (moderate): python-feedparser security update",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://lists.opensuse.org/opensuse-updates/2011-04/msg00026.html"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://bugzilla.novell.com/show_bug.cgi?id=680074"
        },
        {
            "name": "MDVSA-2011:082",
            "tags": [
                "vendor-advisory",
                "x_refsource_MANDRIVA"
            ],
            "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2011:082"
        }
    ]
}