{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--6d636eba-6fb6-49b9-bb07-663f4b44d36a",
    "created": "2024-08-13T16:14:36.93428Z",
    "modified": "2024-08-13T16:14:36.934285Z",
    "name": "No Title Available",
    "description": "FTPServer.py in pyftpdlib before 0.2.0 does not increment the attempted_logins count for a USER command that specifies an invalid username, which makes it easier for remote attackers to obtain access via a brute-force attack.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2007-6737"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=20"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn23&r=23&format=side&path=/trunk/pyftpdlib/FTPServer.py"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://code.google.com/p/pyftpdlib/source/detail?r=23"
        }
    ]
}