{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--d53752f0-bcf1-4590-a649-3f09e6eb59f4",
    "created": "2024-08-13T16:08:08.903004Z",
    "modified": "2024-08-13T16:08:08.903008Z",
    "name": "`CHECK` fail in `tf.linalg.matrix_rank` in TensorFlow",
    "description": "TensorFlow is an open source platform for machine learning. When `tf.linalg.matrix_rank` receives an empty input `a`, the GPU kernel gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit c55b476aa0e0bd4ee99d0f3ad18d9d706cd1260a. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2022-35988"
        }
    ],
    "metrics": [
        {
            "cvssV3_1": {
                "attackComplexity": "HIGH",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 5.9,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "NONE",
                "integrityImpact": "NONE",
                "privilegesRequired": "NONE",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "version": "3.1"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-9vqj-64pv-w55c"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://github.com/tensorflow/tensorflow/commit/c55b476aa0e0bd4ee99d0f3ad18d9d706cd1260a"
        }
    ]
}