{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--c1429e48-4338-401a-9d63-5addcda1e30a",
    "created": "2024-08-13T16:15:24.445797Z",
    "modified": "2024-08-13T16:15:24.445802Z",
    "name": "No Title Available",
    "description": "IBM Cognos Analytics 11.0 and 11.1 could reveal sensitive information to an authenticated user that could be used in future attacks against the system. IBM X-Force ID: 161271.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2019-4334"
        }
    ],
    "metrics": [
        {
            "cvssV3_0": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "NONE",
                "baseScore": 4.3,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "LOW",
                "exploitCodeMaturity": "UNPROVEN",
                "integrityImpact": "NONE",
                "privilegesRequired": "LOW",
                "remediationLevel": "OFFICIAL_FIX",
                "reportConfidence": "CONFIRMED",
                "scope": "UNCHANGED",
                "temporalScore": 3.8,
                "temporalSeverity": "LOW",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/C:L/A:N/S:U/AC:L/AV:N/PR:L/UI:N/I:N/E:U/RL:O/RC:C",
                "version": "3.0"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://www.ibm.com/support/pages/node/1074144"
        },
        {
            "name": "ibm-cognos-cve20194334-info-disc (161271)",
            "tags": [
                "vdb-entry",
                "x_refsource_XF"
            ],
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/161271"
        }
    ]
}