{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--34d7ca52-6b9f-4d5c-ab29-78406fa44280",
    "created": "2024-08-13T16:14:39.45402Z",
    "modified": "2024-08-13T16:14:39.454025Z",
    "name": "No Title Available",
    "description": "The parser cache functionality in parsergenerator.py in RPLY (aka python-rply) before 0.7.1 allows local users to spoof cache data by pre-creating a temporary rply-*.json file with a predictable name.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2014-1604"
        }
    ],
    "references": [
        {
            "name": "[oss-security] 20140114 Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://www.openwall.com/lists/oss-security/2014/01/17/8"
        },
        {
            "name": "rply-cve20141604-insecure-permissions(90593)",
            "tags": [
                "vdb-entry",
                "x_refsource_XF"
            ],
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/90593"
        },
        {
            "name": "102202",
            "tags": [
                "vdb-entry",
                "x_refsource_OSVDB"
            ],
            "url": "http://www.osvdb.org/102202"
        },
        {
            "name": "56429",
            "tags": [
                "third-party-advisory",
                "x_refsource_SECUNIA"
            ],
            "url": "http://secunia.com/advisories/56429"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263"
        },
        {
            "name": "[oss-security] 20140117 Re: Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp",
            "tags": [
                "mailing-list",
                "x_refsource_MLIST"
            ],
            "url": "http://www.openwall.com/lists/oss-security/2014/01/18/4"
        }
    ]
}