{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--604c6b65-9bc8-43d1-8dc8-98d7473719d2",
    "created": "2024-08-13T16:14:00.362031Z",
    "modified": "2024-08-13T16:14:00.362035Z",
    "name": "No Title Available",
    "description": "openshift before versions 3.3.1.11, 3.2.1.23, 3.4 is vulnerable to a flaw when a volume fails to detach, which causes the delete operation to fail with 'VolumeInUse' error. Since the delete operation is retried every 30 seconds for each volume, this could lead to a denial of service attack as the number of API requests being sent to the cloud-provider exceeds the API's rate-limit.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2016-9592"
        }
    ],
    "metrics": [
        {
            "cvssV3_0": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "LOW",
                "baseScore": 4.3,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "NONE",
                "integrityImpact": "NONE",
                "privilegesRequired": "LOW",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                "version": "3.0"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-9592"
        },
        {
            "name": "94991",
            "tags": [
                "vdb-entry",
                "x_refsource_BID"
            ],
            "url": "http://www.securityfocus.com/bid/94991"
        }
    ]
}