{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--e415dd2c-f081-47d8-9910-f80cf25bf98b",
    "created": "2024-08-13T16:11:34.112567Z",
    "modified": "2024-08-13T16:11:34.112571Z",
    "name": "Uncaught Exception in thorsten/phpmyfaq",
    "description": "Uncaught Exception in GitHub repository thorsten/phpmyfaq prior to 3.1.11.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2023-0790"
        }
    ],
    "metrics": [
        {
            "cvssV3_0": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 7.6,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "LOW",
                "integrityImpact": "LOW",
                "privilegesRequired": "LOW",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:H",
                "version": "3.0"
            }
        }
    ],
    "references": [
        {
            "url": "https://huntr.dev/bounties/06af150b-b481-4248-9a48-56ded2814156"
        },
        {
            "url": "https://github.com/thorsten/phpmyfaq/commit/f34d84dfe551ecdd675916e45cc0606e04a0734e"
        }
    ]
}