{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--94113239-9f84-40c9-8c2c-146f56735bee",
    "created": "2024-08-13T16:13:54.640699Z",
    "modified": "2024-08-13T16:13:54.640703Z",
    "name": "No Title Available",
    "description": "web2py before 2.14.6 does not properly check if a host is denied before verifying passwords, allowing a remote attacker to perform brute-force attacks.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2016-10321"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/web2py/web2py/issues/1585#issuecomment-284317919"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://github.com/web2py/web2py/commit/944d8bd8f3c5cf8ae296fc03d149056c65358426"
        },
        {
            "name": "USN-4030-1",
            "tags": [
                "vendor-advisory",
                "x_refsource_UBUNTU"
            ],
            "url": "https://usn.ubuntu.com/4030-1/"
        }
    ]
}