{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--1dfec20c-4dd1-4472-9d43-a9bdb167fe59",
    "created": "2024-08-13T16:05:01.446392Z",
    "modified": "2024-08-13T16:05:01.446395Z",
    "name": "No Title Available",
    "description": "Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2021-35042"
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://groups.google.com/forum/#%21forum/django-announce"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://docs.djangoproject.com/en/3.2/releases/security/"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://www.openwall.com/lists/oss-security/2021/07/02/2"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://www.djangoproject.com/weblog/2021/jul/01/security-releases/"
        },
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://security.netapp.com/advisory/ntap-20210805-0008/"
        },
        {
            "name": "FEDORA-2021-78e501d62a",
            "tags": [
                "vendor-advisory",
                "x_refsource_FEDORA"
            ],
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SS6NJTBYWOX6J7G4U3LUOILARJKWPQ5Y/"
        }
    ]
}