{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--ce42b69a-a5c4-4cc9-8c7f-0b5257b5b0c3",
    "created": "2024-08-13T16:05:54.596434Z",
    "modified": "2024-08-13T16:05:54.596439Z",
    "name": "Business Logic Errors in yetiforcecompany/yetiforcecrm",
    "description": "yetiforcecrm is vulnerable to Business Logic Errors",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2021-4117"
        }
    ],
    "metrics": [
        {
            "cvssV3_0": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "NONE",
                "baseScore": 7.7,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "NONE",
                "integrityImpact": "HIGH",
                "privilegesRequired": "LOW",
                "scope": "CHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:H/A:N",
                "version": "3.0"
            }
        }
    ],
    "references": [
        {
            "tags": [
                "x_refsource_CONFIRM"
            ],
            "url": "https://huntr.dev/bounties/0b81e572-bdc9-4caf-aa02-81f3c7ad7c0a"
        },
        {
            "tags": [
                "x_refsource_MISC"
            ],
            "url": "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239"
        }
    ]
}